name: 'Scheduled JSON Updates'
on:
  schedule:
    - cron: '0 22 * * *'

jobs:
  # Wait for up to two minutes for previous workflow run to complete, abort if not done by then
  pre-ci:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: 'Block Concurrent Executions'
        uses: softprops/turnstyle@v1
        with:
          poll-interval-seconds: 15
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  trigger-updates-json:
    # For this job to work, the following secrets must be set:
    # SITE_DISPATCH_ACCESS_TOKEN
    name: 'Trigger Info Update'
    runs-on: ubuntu-latest
    if: (github.repository == 'Warzone2100/update-data')
    needs: pre-ci
    steps:
      - name: 'Trigger scheduled data update'
        run: |
          curl -X POST https://api.github.com/repos/Warzone2100/update-data/dispatches \
          -H 'Accept: application/vnd.github.everest-preview+json' \
          -u ${{ secrets.WZ2100_UPDATES_PUSH_TOKEN }} \
          --data '{"event_type": "scheduled_update", "client_payload": { "repository": "'"$GITHUB_REPOSITORY"'" }}'
